import collections,datetime,hashlib,json,pathlib
import search as s
O=s.O

def main():
 get=lambda p:json.loads((O/p).read_text());summary=get('summary.json');ctr=get('controls/controls.json');add=get('additional-controls.json');r2=get('r02/controls.json');runs=[json.loads(p.read_text()) for p in (O/'runs').glob('*/command.json')];plan=get('r02/f-plan.json');kd=get('r02/keys.json');pc=get('replay-results.json');metrics=dict(stages=summary['stages'],total_logged_seconds=sum(x.get('duration_seconds',0) for x in runs),runs=[dict(label=pathlib.Path(x['command'][-1]).name if x.get('command') else '',seconds=x.get('duration_seconds'),outcome=x['outcome']) for x in runs],R01_F_control=dict(rank=ctr['truth_recipe_rank'],plant=next({k:x[k] for k in ['recipe','sign','score','errors','truth_in_top16']} for x in ctr['selection'] if x['recipe']=='DIVINITY' and x['sign']==-1),corrupt=ctr['corrupted_first_key']),R01_more_controls=[{k:x[k] for k in ['mode','truth_rank','planted_errors','best_errors','rejected_keys','corrupted_first_key_errors']} for x in add['controls']],affine=add['affine'],R02_controls=[{k:x[k] for k in ['mode','ordinary_trials','F_trials','planted_rigid_rank','planted_survived','truth_hypothesis_rank','best_errors','planted_errors','truth_in_planted_top16','corrupted_key_errors']} for x in r2['results']],keys=len(kd['keys']),running_texts=len(kd['texts']),phase_sum=sum(len(k['key']) for k in kd['keys']),F_shortlist=len(plan['shortlist']),F_independent=len(plan['independent_fixed']),F_union=len(plan['queue']),widened=add['widened'],widened_changed=add['widened_best_changed'],replays=len(pc));s.dump(O/'metrics.json',metrics)
 parts=['# Worker A — R01 / R02 final report','','No credible new text recovered. The retained outputs remain score-ranked noise candidates, all UNREVIEWED pending the separate reviewer. No score is a solve; no cipher family is excluded.','',f'All 45 discovery original pages were processed, including original55. The initial <=54 cutoff omitted55; preserved legacy44-page files were followed by separate -p55 catchups. Reserved4,9,14,19,24,29,34,39,44,54 were never decoded. Full frozen source-page rune sequences were used throughout, without prefix cuts.','',f'Logged processing so far: {metrics["total_logged_seconds"]:.2f} seconds across {len(runs)} recorded invocations (last report invocation still running is excluded from its own elapsed total). All search/checkpoint stages completed; no search process remains active. Single compute job, one thread. Initial60-minute allowance not exhausted because finite searches ran quickly.','', '| Stage | Executed / planned | Best quadgram |','|---|---:|---:|']
 for x in summary['stages']:parts.append(f'| {x["stage"]} | {x["cursor"]} / {x["total"]} | {x["best"]:.6f} |')
 parts+=['','## R01 coverage','', 'Four frozen recipes: DIVINITY period8, literal FIRFUMFERENFE period13, PRIMES and the frozen TOTIENTS array (prime-minus-one, not integer totients). Both signs p=(c+sign*k) mod29. Ordinary and literal-F cover every periodic phase and numeric offsets0..127 on all45 pages. F startzero was searched first at width256. Full affine812 transforms per page is a deliberate baseline recheck. R01 real trials87120 include360 ordinary startzero duplications across initial/start-offset batches, plus10 width1024 selected followups. Unique specified ordinary/F/affine/rejection cells86760. Legacy repetition-rejection covers all360 recipe/sign/page cells at offsetzero only, beam400 and maxskip3. No cross-product of affine and F.','', 'Literal-F emits rune0 and does not consume key. Beam prunes by normalized prefix Latin quadgrams, stable tie order; pruning counts and discarded-cutoff ties are recorded for retained candidates. It is separate from repeat-rejection, which accepts skipped key positions only when each would encrypt the current plaintext rune to the preceding ciphertext rune. Legacy rejection uses cumulative beam scoring, normalized final reporting, and independently checked fixed-path re-encryption for every real result. No combined mechanisms.','',f'R01 full solved WELCOME fixture, eight signed-recipe F hypotheses: planted rank{metrics["R01_F_control"]["rank"]}, best planted rune errors{metrics["R01_F_control"]["plant"]["errors"]}, truth in retained top16={metrics["R01_F_control"]["plant"]["truth_in_top16"]}. Three exact reference arithmetic fixtures passed. Corrupt first-key check produced{metrics["R01_F_control"]["corrupt"]["errors"]} errors.', '']
 for x in metrics['R01_more_controls']:parts.append(f'{x["mode"]} eight-hypothesis control: true rank{x["truth_rank"]}, planted errors{x["planted_errors"]}, top errors{x["best_errors"]}, actual rejected keys{x["rejected_keys"]}; corrupt first-key errors{x["corrupted_first_key_errors"]}.')
 parts += [f'Full812 affine search control true rank{add["affine"]["truth_rank"]}, errors{add["affine"]["planted_errors"]}.','', '## R02 coverage','',f'Frozen {metrics["keys"]} distinct exact rune arrays from ordered one/two-word phrases, length4..32, in verified solved sources. Source character ranges, verbatim rune phrases, aliases and exact conversion are in r02/keys.json. No Latin digraph crosses word boundaries because conversion uses source runes directly. The first256 distinct source-ordered phrases were accepted before real scoring; this prioritizes early listed sources and does not represent all solved-text phrases. All within-period phases ({metrics["phase_sum"]} phase cells) and both signs were run at each of45 page boundaries.','',f'Eight short solved source texts were also used as finite running keys at natural/source-line starts. Each source is an internal documented clue connection, all already held locally; offsets are listed in keys.json, at most1024 each. No running-key wrapping/padding or insufficient-key trials. Total ordinary186056 = {metrics["phase_sum"]*90} periodic cells + {186056-metrics["phase_sum"]*90} valid running-text cells. Literal-F covered only top256 ordinary cells plus fixed independent Random(330102) sample256: union512. That weak ordinary filter does not cover discarded F cases. F width1024 reran ten selected cases per lane; no selected best output changed.', '']
 for x in metrics['R02_controls']:parts.append(f'R02 {x["mode"]} control: ordinary pool{x["ordinary_trials"]}, expensiveF{x["F_trials"]}, planted rigid rank{x["planted_rigid_rank"]}, survived{x["planted_survived"]}, final hypothesis rank{x["truth_hypothesis_rank"]}, planted/top errors{x["planted_errors"]}/{x["best_errors"]}, truth retained{x["truth_in_planted_top16"]}; corrupt first-key errors{x["corrupted_key_errors"]}.')
 parts+=['','## Retention and limits','',f'Deduplicated final exports R01/top_candidates.json and r02/top_candidates.json retain every stage top plus R02 ordinary shortlist (more than20 each), preserving equivalent origins. Separate fixed-rule replay.py reproduced all{len(pc)} retained candidate outputs and every stored F alternative. Alternatives may number below16 when the complete compatible population is smaller. Full raw output, rune positions, keys or key references, path choices, scores and replay manifests are retained. Candidate files were handed to the fresh reviewer; worker replay is arithmetic verification, not independent validation.','', 'All sweep score tables are compressed JSONL and resumable cursor checkpoints persist candidate ordinals and exact enumerators. R01 legacy44-page IDs remain unchanged; p55 uses separate directory-qualified IDs. Append-only unique logger directories contain PID/start/end/exit/source snapshots and hashes. Minor setup patch invocations are logged. No old evidence was modified.','', 'Scores are English transliteration quadgrams and are length-sensitive; shorter pages rank conspicuously well and cross-page top ranks are not calibrated evidence. IoC*N, minimum distinct32-rune symbols and zlib ratio are persisted for every sweep candidate. Non-English LM is unavailable/null. A delimiter-aware exact-rune solved-word fraction is descriptive only, added before p55 and R02 searches; not present on earlier44-page rows, and not independent of the solved-text register. Source slash lines are provisional; no image-boundary certainty is claimed.','', 'Coverage is conditional on exactly the listed key spaces, ordinary/literal-F/repeat-rejection transition relations, and English register. Small successful controls do not establish universal power, nor do a first-key corruption or incidental words calibrate a false-discovery threshold. No holdout reveal, no sustained-text candidate, no unsupported p-value.','', '## Resume and replay','', 'The finite queue is complete. There is nothing left running. To verify retained fixed rules:','```sh','.venv/bin/python -B exploration/overnight-01/run_logged.py --owner exploration/overnight-01/worker-a --label replay-again --input exploration/overnight-01/config.json --input audit/parallel-01/inputs/dataset.json --input audit/experiment-01/keys.json --input exploration/overnight-01/worker-a/r02/keys.json --seconds 900 -- .venv/bin/python -B exploration/overnight-01/worker-a/replay.py','```','', 'Search stage commands and immutable code snapshots are in runs/*/command.json and runs/*/code/. For a partial checkpoint, the same command resumes from its saved cursor. Completed cursors are not a request to rerun. A fresh expansion requires its own named finite plan, such as broader F-only clue coverage independent of ordinary ranking; the current noise does not justify a sweeping expansion.']
 (O/'REPORT.md').write_text('\n'.join(parts)+'\n')
 for lane in ['R01','R02']:
  (O/('r02' if lane=='R02' else lane)/'REPORT.md').write_text('# '+lane+'\n\nSee ../REPORT.md for complete lane coverage, controls, limitations and replay commands. Candidates: top_candidates.json. Status: finite queue complete; no credible new text.\n')
 for lane in ['R01','R02']:
  rows=get(('r02' if lane=='R02' else lane)+'/top_candidates.json');print(json.dumps(dict(lane=lane,retained=len(rows),top=[dict(id=r['id'],page=r['original_page'],n=len(r['plain_idx']),score=r['scores']['english_quadgram'],text=r['translit'][:250]) for r in rows[:3]])))
 print(json.dumps({k:v for k,v in metrics.items() if k not in ['runs','affine','stages']}))
if __name__=='__main__':main()
