"""One-time reviewed claim update; preserves claims, sources and T1 evidence history."""
import json
from pathlib import Path
U={
1:('INDEPENDENTLY_SUPPORTED','Independent A and D parsers and fresh reviewer reproduce 12956 runes and pinned normalized hash.','Whole-image transcription correctness; all non-rune material','Use frozen inputs-v1 for bounded rune experiments.'),
2:('INDEPENDENTLY_SUPPORTED','58-image/57-segment map published; targeted p49–51,55–57 transitions verified. p50 contains 13 alphanumeric rows, not an empty page.','Other image joins remain provisionally inherited; exhaustive spatial inventory','Verify additional page regions before claiming complete puzzle-input coverage.'),
3:('SOURCE_CHECKED','All13136 rune arrays agree across three local transcriptions; historical shared ancestry remains reported, not independently reconstructed.','Universal source genealogy; independent blind glyph ground truth','Do not count agreement as three independent witnesses.'),
4:('SOURCE_CHECKED','Targeted unblinded glyph checks added, including p57 rune80 Y; inherited180/180 and450/450 studies not rerun.','Full historical control sample and blind accuracy','Assign an independent transcription control before extending visual accuracy claims.'),
5:('SOURCE_CHECKED','Independent one-substitution sensitivity measured; it does not validate the inherited indel confidence ceiling.','Insertion/deletion population and systematic transcription errors','Keep R19 indel limits conditional and unaudited.'),
6:('SOURCE_CHECKED','Separators and slash-lines retained; count86 splits60 literal,22 separator,4 line-join pairs.','Inherited19 separator adjudications and24 residual-line claims','Verify separator geometry separately from rune-stream counting.'),
7:('INDEPENDENTLY_SUPPORTED','58/58 actual image SHA1s match freshly retrieved archive metadata, extending the stated56-file comparison.','Authorship authenticity, steganography absence, transcription accuracy','Retain byte identity only; no broader image-content inference.'),
8:('INDEPENDENTLY_SUPPORTED','Nine complete external reference groups2979runes pass independent rules, eight hand checks and11mutations. Original five-word anchor remains narrow; inherited outputs have whole-output failures.','Certified LP1 physical page cuts; independently transcribed expected answers','Use full-rune fixtures as controls for a separately authorised production repair.'),
9:('REPRODUCED','Seven inherited scripts exit PASS; only3 outputs equal full reference groups. Three keyed outputs delete F; WELCOME also wrong interruption path; koan omits38runes.','Automatic interruption finder correctness and all image content','Repair inherited known-solution fidelity separately against complete fixtures.'),
10:('REPRODUCED','Inherited selftest repeated once for detector comparison; fresh reset English cases40/40 accepted,79/80 pages exact. Blinded8-key search240/240 runes correct.','CLI real-input path; population-wide search sensitivity','Use only the bounded measured setup, with actual candidate-key controls.'),
11:('INDEPENDENTLY_SUPPORTED','Executable check finds4096 copies of27 versus29 unique symbols from a persistent RNG;200 varied negatives measured separately.','False acceptance outside the measured fixed-text/key distributions','Retain constant control separately and varied-key controls in future repairs.'),
12:('INDEPENDENTLY_SUPPORTED','Call trace starts both pages at0;20/20 continuous-key cases rejected. Supplying true starts recovers99.979% runes.','Offset search, arbitrary page-specific keys and their calibration','Continuous-key searches require an independently tested interface.'),
13:('INDEPENDENTLY_SUPPORTED','Independent skip-by-two challenge: legacy only2/20 PASS,1/40 exact selected pages; two PASS cases have substantial errors.','Other rejection constructions and parameter settings','Label legacy transition limits unsupported rather than cipher impossibility.'),
14:('INDEPENDENTLY_SUPPORTED','Vowel-removed truth scores below English bar;20/20 rejected, including two exactly recovered correct-sign pages.','Other language registers and historical Latin/Welsh power values','Use register-specific controls before interpreting a negative.'),
15:('INDEPENDENTLY_SUPPORTED','Full signs/decoders/pages selection replayed on100 varied negatives per length and100 paired shuffles. Full-max lift over narrow null measured; no varied wrong key accepted.','Candidate-set maxima, real-input tail law, large searches','Calibrate the full proposed candidate set; PASS is a flag, not proof.'),
16:('INDEPENDENTLY_SUPPORTED','threshold_for returns identical value for lengths1,31,60,120,400,12956 andNone at fixed trials.','Universal tail validity of historical constants','Freeze and calibrate exact length/configuration for any new experiment.'),
17:('INDEPENDENTLY_SUPPORTED','R19 pair preset39/40 skip-by-two pages exact,99.979% rune recovery on fresh plants.','Historical gates and wrong-key rates; permissive drift/offset settings','Require full R19 negative calibration before using it for searches.'),
18:('BLOCKED','Actual I2 panel load blocked: models/panel.npz absent. No training rebuild or new27-cell power claim.','Current end-to-end multi-register power and runtime','Recover a pinned model or authorise a separate reproducible rebuild.'),
19:('SOURCE_CHECKED','Retained R21 table arithmetic checked: best safe tuning36/45, held-out54/66, false rejects4/24.','Regeneration of the population and executable certification pipeline','Keep failed seal and historical provenance attached to the reported arithmetic.'),
20:('INDEPENDENTLY_SUPPORTED','Independent parser and reviewer reproduce all86 positions:86/12955 flat,86/12901 withinpage;60/9640 literal,22/2722 separators,4/539 lines,0/54 pagejoins.','Image transcription; systematic error; verified section grouping','Use explicit boundary convention and frozen rune-only input.'),
21:('INDEPENDENTLY_SUPPORTED','Entropy4.85650361370827 and IoC×29=.999873538070665 independently reproduced.','Higher-order laws or cryptographic security','Retain marginal measurements without key-length inference.'),
22:('INDEPENDENTLY_SUPPORTED','Conditional convolution inequality derived and handchecked. Dependent-increment counterexample refutes removing independence; expectation is not a finite-sample certainty.','Justified plaintext distribution and dependence-aware tail bound','Name independence, position conditioning and sample law before any exclusion.'),
23:('SOURCE_CHECKED','Historical English/German corpus floors not remeasured; finite text samples cannot establish a universal language floor.','Exact historical corpus hashes/windows and their reported numbers','Reproduce a named corpus/window only when needed for a bounded hypothesis.'),
24:('INCONCLUSIVE','Same output law can arise from rejection sampling or direct Markov transitions; low repeats cannot uniquely identify internal filter. Empirical uniform-baseline deficit80.7487% differs from fitted rejection probability.','Actual LP mechanism, including whether it uses any filter','Treat filter as a test model, not a pinned explanation.'),
25:('CONTRADICTED','Unconditional full-length necessity contradicted by balanced deterministic plaintext with one-symbol key and flat marginal statistics. Historical period400 result not rerun.','Language-constrained model-specific exclusion; historical period ladder','Reopen unconditional key-length closure; retain only specified simulated bounds.'),
26:('INCONCLUSIVE','Finite-battery non-separation does not identify OTP-class membership or establish perfect secrecy. No preferred replacement theory inferred.','Actual cipher class and full observation-law security proof','Evaluate finite hypotheses with controls without treating OTP-class as established.'),
27:('CONTRADICTED','Explicit resetting-key/carrying-filter example has no boundary repeat. 0/54 has probability.150329 under uniform independent joins; it does not establish continuity.','Actual puzzle reset policy','Keep reset and continuous constructions separate, neither established.'),
37:('REPRODUCED','Six temporary fixture cases reproduce original parent0 even on failures; repaired parent0 only all-success and1 for exit1/2,signal,timeout,launcherror. Fresh reviewer confirms; import inert.','No real failed T0 child existed; no broad new wrapper framework tested','Repair complete; retain child outcome distinctions and regression cases.')}
GROUP=lambda n:'inputs' if n<=7 else 'reference' if n<=9 else 'detectors' if n<=19 else 'statistics' if n<=27 else 'runner'
p=Path('audit/CLAIMS.jsonl');rows=[json.loads(x) for x in p.read_text().splitlines()]
for r in rows:
 n=int(r['id'][2:])
 if n not in U:continue
 status,result,limits,nextcheck=U[n];group=GROUP(n);report=f'audit/parallel-01/{group}/REPORT.md'
 assert 'PARALLEL-01' not in r['tested_scope'],'Do not overwrite integration history'
 r.setdefault('audit_history',[]).append({'task':'T1','status':r['status'],'observed_result':r['observed_result'],'not_tested':r['not_tested'],'next_check':r['next_check']})
 r['status']=status;r['observed_result']=result;r['not_tested']=[limits];r['next_check']=nextcheck
 r['tested_scope']['PARALLEL-01']={'result':result,'limits':limits,'report':report,'review':'audit/parallel-01/review/REPORT.md','input_commit':'95e11e918ace77a51de4b612a48e74c298e67e58'}
 r['evidence_paths']+= [report,'audit/parallel-01/review/REPORT.md']
 if n==37:r['implementation_status']='REPAIRED_AFTER_DEFECT_REPRODUCTION'
p.write_text(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in rows))
index=['# Audit claim index after PARALLEL-01','','Claims and original source excerpts are retained. Status applies only to the scoped evidence in the JSONL record; it never implies archive-wide or image-wide validation. T1 states remain in audit_history. In particular, C-025/C-027 counterexamples refute claimed implications, not prove the actual cipher uses short keys or resets.','','| ID | Kind | Status | Inherited claim |','| --- | --- | --- | --- |']
index += [f"| {r['id']} | {r['kind']} | {r['status']} | {r['claim'].replace('|','/')} |" for r in rows]
Path('audit/CLAIM-INDEX.md').write_text('\n'.join(index)+'\n')
print(json.dumps({'updated_claims':len(U),'retained_claims':len(rows),'status_counts':{s:sum(r['status']==s for r in rows) for s in sorted({r['status'] for r in rows})}},indent=2))
